### ISSUE TITLE
OAuth2 or Saml or OpenID Connect Integration

### ISSUE THREAD

**Issue by hbadri3** [raseel-internal/ckanext-raseel-theme2#44]
We will look at one of those two:

- https://github.com/bcgov/ckanext-sso

- https://github.com/conwetlab/ckanext-oauth2

**Comment by hbadri3** [comment]
https://github.com/conwetlab/ckanext-oauth2 this one does not support ckan 2.9 neither python 3

**Comment by hbadri3** [comment]
https://github.com/bcgov/ckanext-sso this one also does not support python 3

**Comment by meriam1996** [comment]
https://github.com/keitaroinc/ckanext-saml2auth  this one support Ckan 2.9 +

**Comment by hbadri3** [comment]
As u suggested let's try to upgrade https://github.com/conwetlab/ckanext-oauth2

**Comment by hbadri3** [comment]
Wont fix
