### ISSUE TITLE
Organizations page has issue in mobile version

### ISSUE THREAD

**Issue by hbadri3** [raseel-internal/ckanext-raseel-theme2#96]
Related to responsiveness

**Comment by meriam1996** [comment]
issue resolved

**Comment by hbadri3** [comment]
@meriam1996 when I click to Raseel Logo in mobile version It takes me to mda.gov.sa.

Let's also disable the click on MDA logo in navbar (no need to lead to MDA website

**Comment by hbadri3** [comment]
Resolved
